components:
  devtron:
    ingress:
      enabled: true
      className: nginx
      host: devtron.127.0.0.1.nip.io
installer:
  modules:
    - cicd
  arch: multi-arch
argo-cd:
  enabled: true
security:
  enabled: true
  trivy:
    enabled: true
notifier:
  enabled: true
monitoring:
  grafana:
    enabled: true
minio:
  enabled: true
